---
query_config:
    max_threads:      120
    data_type:        branch
    github_org:       cloudify-cosmo
    output_path:      /home/avia/tattle/output/report.json

filters:
  - type: name
    precedence: 1
    regular_expressions: [CFY]
        
  - type: issue
    precedence: 2
    jira_team_name: cloudifysource
    jira_statuses:  [Closed, Resolved]
    transform:
        base:               CFY-*\d+
        if_doesnt_contain:  '-'
        replace_from:       CFY
        replace_to:         CFY-
...
